<?php
/**
 * Created by PhpStorm.
 * User: abpopov
 * Date: 25.08.15
 * Time: 12:47
 */

namespace common\components\controllers;

use common\models\ExternalSite;
use Yii;
use yii\web\Controller;

class FrontendController extends Controller {



	public  function  sendJSONResponse($data,$httpStatus=200,$isError=null){
        \Yii::$app->response->format = 'json';
        return $data;

    }


    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub


        $cookies = \Yii::$app->request->cookies;

        if (isset($cookies['site'])) {
            $id =  $cookies['site']->value;

            if ($id!=-1){


                $this->view->params['site_id']=$id;

            }


        }else{


            $domain_name =   Yii::$app->request->getHostName();

            $external_site= ExternalSite::find()->where(["url"=>$domain_name])->one();


            //print_r($external_site);
            //exit;
            if ($external_site){

                $cookies = \Yii::$app->response->cookies;
                $cookies->add(new \yii\web\Cookie([
                    'name' => 'site',
                    'value' =>$external_site->id,
                ]));

                $this->view->params['site_id']=$external_site->id;


            }else{

                $cookies = \Yii::$app->response->cookies;
                $cookies->add(new \yii\web\Cookie([
                    'name' => 'site',
                    'value' => -1,
                ]));
            }


        }







    }
}
