<?php
/**
 * Created by PhpStorm.
 * User: anatoliypopov
 * Date: 02/12/2016
 * Time: 11:29
 */

namespace backend\models\forms;


use common\models\Region;
use common\models\Restaurant;
use common\models\Tag;
use yii\base\Model;
use yii\helpers\ArrayHelper;

class RestaurantForm extends Model
{

    public $id;
    public  $address;
    public  $region_id;
    public  $phone;
    public  $lat;
    public  $lng;
    public  $metro;
    public  $is_active;
    public  $external_id;
    public  $tags;
    public $organisation;

    public  $searchTitle;

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['address', 'lat', 'lng','external_id'], 'required'],
            [['region_id'], 'integer'],
            [['lat', 'lng'], 'number'],
            [['metro'], 'string'],
            [['is_active'], 'boolean'],
            ['tags','safe'],
            ['organisation','safe'],
            [['address', 'phone'], 'string', 'max' => 255],
            [['region_id'], 'exist', 'skipOnError' => true, 'targetClass' => Region::className(), 'targetAttribute' => ['region_id' => 'id']],
        ];
    }


    /**
     * @param Restaurant $restaurant
     * @return bool
     */

    public  function saveItem($restaurant){

        if ($this->validate()){



            $restaurant->address=$this->address;
            $restaurant->phone=$this->phone;
            $restaurant->lat=$this->lat;
            $restaurant->lng=$this->lng;
            $restaurant->region_id=$this->region_id;
            $restaurant->external_id=$this->external_id;
            $restaurant->metro=$this->metro;

            $restaurant->organisation_id=$this->organisation;

            if ($restaurant->save()){


                $restaurant->unlinkAll('tags',true);
                if ($this->tags && count($this->tags)>0){



                    foreach ($this->tags as $tag_id){

                        if ($tag = Tag::findOne($tag_id)){

                            $tag->link('restaurants',$restaurant);

                        }


                    }

                }

                return true;

            }

        }


        return false;
    }

    /**
     * @return bool|Restaurant
     */

    public  function createRestaurant(){

        if ($this->validate()){

            $restaurant = new Restaurant();

            $restaurant->address=$this->address;
            $restaurant->phone=$this->phone;
            $restaurant->lat=$this->lat;
            $restaurant->lng=$this->lng;
            $restaurant->region_id=$this->region_id;
            $restaurant->metro=$this->metro;
            $restaurant->external_id=$this->external_id;
            $restaurant->organisation_id=$this->organisation;

            if ($restaurant->save()){

                if ($this->tags && count($this->tags)>0){

                    foreach ($this->tags as $tag_id){

                        if ($tag = Tag::findOne($tag_id)){

                            $tag->link('restaurants',$restaurant);

                        }


                    }

                }

                return $restaurant;

            }
            else{

                print_r($restaurant->getErrors());
                exit();
            }

        }


        return false;
    }

    public function loadFromModel(Restaurant $restaurant){


        $this->address = $restaurant->address;
        $this->phone= $restaurant->phone;
        $this->lng=$restaurant->lng;
        $this->lat=$restaurant->lat;
        $this->region_id = $restaurant->region_id;
        $this->metro=$restaurant->metro;
        $this->external_id=$restaurant->external_id;
        $this->tags= ArrayHelper::getColumn($restaurant->getTags()->asArray()->all(), 'id');
        $this->organisation=$restaurant->organisation_id;
    }

    public function attributeLabels()
    {
        return parent::attributeLabels(); // TODO: Change the autogenerated stub
    }
}